-- Add session metadata columns
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "last_activity" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
